// This file is auto-generated by @hey-api/openapi-ts

export {
  type AddRatingRequestModel,
  addRatingRequestSchema,
  type CastMemberModel,
  castMemberSchema,
  type MovieCreateRequestModel,
  movieCreateRequestSchema,
  type MovieDetailsResponseModel,
  movieDetailsResponseSchema,
  type MovieGenreModel,
  movieGenreSchema,
  type MovieRatingInfoModel,
  movieRatingInfoSchema,
  type SseItemOfAddRatingRequestModel,
  sseItemOfAddRatingRequestSchema,
} from './zod.gen';
