// This file is auto-generated by @hey-api/openapi-ts

export const AddRatingRequestSchema = {
  type: 'object',
  properties: {
    movie: {
      $ref: '#/components/schemas/MovieRatingInfo',
    },
    rating: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int32',
    },
  },
} as const;

export const CastMemberSchema = {
  required: ['name', 'role'],
  type: 'object',
  properties: {
    name: {
      maxLength: 50,
      minLength: 1,
      type: 'string',
    },
    role: {
      maxLength: 50,
      minLength: 1,
      type: 'string',
    },
  },
} as const;

export const MovieCreateRequestSchema = {
  required: ['title', 'director', 'releaseDate', 'genre', 'ratings', 'duration'],
  type: 'object',
  properties: {
    title: {
      maxLength: 100,
      minLength: 1,
      type: 'string',
    },
    director: {
      maxLength: 100,
      minLength: 1,
      type: 'string',
    },
    releaseDate: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int32',
    },
    genre: {
      $ref: '#/components/schemas/MovieGenre',
    },
    ratings: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int32',
    },
    cast: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/CastMember',
      },
    },
    duration: {
      maximum: 500,
      minimum: 1,
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int32',
    },
  },
} as const;

export const MovieDetailsResponseSchema = {
  required: ['id', 'title', 'director', 'releaseDate', 'genre', 'ratings', 'duration'],
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    title: {
      maxLength: 100,
      minLength: 1,
      type: 'string',
    },
    director: {
      maxLength: 100,
      minLength: 1,
      type: 'string',
    },
    releaseDate: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int32',
    },
    genre: {
      $ref: '#/components/schemas/MovieGenre',
    },
    ratings: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int32',
    },
    cast: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/CastMember',
      },
    },
    duration: {
      maximum: 500,
      minimum: 1,
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int32',
    },
  },
} as const;

export const MovieGenreSchema = {
  enum: ['Comedy', 'Action', 'Drama', 'Horror', 'SciFi'],
} as const;

export const MovieRatingInfoSchema = {
  required: ['id', 'version'],
  type: 'object',
  properties: {
    id: {
      type: 'string',
    },
    version: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int32',
    },
  },
} as const;

export const SseItemOfAddRatingRequestSchema = {
  type: 'object',
  properties: {
    data: {
      $ref: '#/components/schemas/AddRatingRequest',
    },
    eventType: {
      type: ['null', 'string'],
    },
    eventId: {
      type: ['null', 'string'],
    },
    reconnectionInterval: {
      pattern: '^-?(\\d+\\.)?\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,7})?$',
      type: ['null', 'string'],
    },
  },
} as const;
