// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  GetApiMoviesByIdData,
  GetApiMoviesByIdErrors,
  GetApiMoviesByIdResponses,
  GetApiMoviesData,
  GetApiMoviesRatingsChannelData,
  GetApiMoviesRatingsChannelResponses,
  GetApiMoviesResponses,
  PostApiMoviesData,
  PostApiMoviesErrors,
  PostApiMoviesRatingsData,
  PostApiMoviesRatingsResponses,
  PostApiMoviesResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const getApiMovies = <ThrowOnError extends boolean = true>(
  options?: Options<GetApiMoviesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiMoviesResponses, unknown, ThrowOnError>({
    url: '/api/movies',
    ...options,
  });

export const postApiMovies = <ThrowOnError extends boolean = true>(
  options: Options<PostApiMoviesData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostApiMoviesResponses, PostApiMoviesErrors, ThrowOnError>({
    url: '/api/movies',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getApiMoviesById = <ThrowOnError extends boolean = true>(
  options: Options<GetApiMoviesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetApiMoviesByIdResponses, GetApiMoviesByIdErrors, ThrowOnError>({
    url: '/api/movies/{id}',
    ...options,
  });

export const postApiMoviesRatings = <ThrowOnError extends boolean = true>(
  options: Options<PostApiMoviesRatingsData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostApiMoviesRatingsResponses, unknown, ThrowOnError>({
    url: '/api/movies/ratings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getApiMoviesRatingsChannel = <ThrowOnError extends boolean = true>(
  options?: Options<GetApiMoviesRatingsChannelData, ThrowOnError>,
) =>
  (options?.client ?? client).sse.get<GetApiMoviesRatingsChannelResponses, unknown, ThrowOnError>({
    url: '/api/movies/ratings-channel',
    ...options,
  });
