// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://localhost:7284/' | (string & {});
};

export type AddRatingRequest = {
  movie?: MovieRatingInfo;
  rating?: number | string;
};

export type CastMember = {
  name: string;
  role: string;
};

export type MovieCreateRequest = {
  title: string;
  director: string;
  releaseDate: number | string;
  genre: MovieGenre;
  ratings: number | string;
  cast?: Array<CastMember>;
  duration: number | string;
};

export type MovieDetailsResponse = {
  id: string;
  title: string;
  director: string;
  releaseDate: number | string;
  genre: MovieGenre;
  ratings: number | string;
  cast?: Array<CastMember>;
  duration: number | string;
};

export type MovieGenre = 'Comedy' | 'Action' | 'Drama' | 'Horror' | 'SciFi';

export type MovieRatingInfo = {
  id: string;
  version: number | string;
};

export type SseItemOfAddRatingRequest = {
  data?: AddRatingRequest;
  eventType?: null | string;
  eventId?: null | string;
  reconnectionInterval?: null | string;
};

export type GetApiMoviesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/movies';
};

export type GetApiMoviesResponses = {
  /**
   * OK
   */
  200: Array<MovieDetailsResponse>;
};

export type GetApiMoviesResponse = GetApiMoviesResponses[keyof GetApiMoviesResponses];

export type PostApiMoviesData = {
  body: MovieCreateRequest;
  path?: never;
  query?: never;
  url: '/api/movies';
};

export type PostApiMoviesErrors = {
  /**
   * Bad Request
   */
  400: string;
};

export type PostApiMoviesError = PostApiMoviesErrors[keyof PostApiMoviesErrors];

export type PostApiMoviesResponses = {
  /**
   * Created
   */
  201: MovieDetailsResponse;
};

export type PostApiMoviesResponse = PostApiMoviesResponses[keyof PostApiMoviesResponses];

export type GetApiMoviesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/movies/{id}';
};

export type GetApiMoviesByIdErrors = {
  /**
   * Not Found
   */
  404: unknown;
};

export type GetApiMoviesByIdResponses = {
  /**
   * OK
   */
  200: MovieDetailsResponse;
};

export type GetApiMoviesByIdResponse = GetApiMoviesByIdResponses[keyof GetApiMoviesByIdResponses];

export type PostApiMoviesRatingsData = {
  body: AddRatingRequest;
  path?: never;
  query?: never;
  url: '/api/movies/ratings';
};

export type PostApiMoviesRatingsResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiMoviesRatingsChannelData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/movies/ratings-channel';
};

export type GetApiMoviesRatingsChannelResponses = {
  /**
   * OK
   */
  200: SseItemOfAddRatingRequest;
};

export type GetApiMoviesRatingsChannelResponse =
  GetApiMoviesRatingsChannelResponses[keyof GetApiMoviesRatingsChannelResponses];
