// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zCastMember = z.object({
  name: z.string().min(1).max(50),
  role: z.string().min(1).max(50),
});

export const zMovieGenre = z.enum(['Comedy', 'Action', 'Drama', 'Horror', 'SciFi']);

export const zMovieCreateRequest = z.object({
  title: z.string().min(1).max(100),
  director: z.string().min(1).max(100),
  releaseDate: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
  genre: zMovieGenre,
  ratings: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
  cast: z.optional(z.array(zCastMember)),
  duration: z.union([z.int().gte(1).lte(500), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
});

export const zMovieDetailsResponse = z.object({
  id: z.uuid(),
  title: z.string().min(1).max(100),
  director: z.string().min(1).max(100),
  releaseDate: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
  genre: zMovieGenre,
  ratings: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
  cast: z.optional(z.array(zCastMember)),
  duration: z.union([z.int().gte(1).lte(500), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
});

export const zMovieRatingInfo = z.object({
  id: z.string(),
  version: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
});

export const zAddRatingRequest = z.object({
  movie: z.optional(zMovieRatingInfo),
  rating: z.optional(z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])),
});

export const zSseItemOfAddRatingRequest = z.object({
  data: z.optional(zAddRatingRequest),
  eventType: z.optional(z.union([z.null(), z.string()])),
  eventId: z.optional(z.union([z.null(), z.string()])),
  reconnectionInterval: z.optional(
    z.union([z.null(), z.string().regex(/^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$/)]),
  ),
});

export const zGetApiMoviesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zGetApiMoviesResponse = z.array(zMovieDetailsResponse);

export const zPostApiMoviesData = z.object({
  body: zMovieCreateRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Created
 */
export const zPostApiMoviesResponse = zMovieDetailsResponse;

export const zGetApiMoviesByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zGetApiMoviesByIdResponse = zMovieDetailsResponse;

export const zPostApiMoviesRatingsData = z.object({
  body: zAddRatingRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetApiMoviesRatingsChannelData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zGetApiMoviesRatingsChannelResponse = zSseItemOfAddRatingRequest;
